package no.entur.abt.bob.mts7.simple.reader;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.security.SecureRandom;
import java.util.Random;

import no.entur.abt.bob.mts7.api.Mts7Exception;
import no.entur.abt.bob.mts7.api.UnableToSelectApplicationException;
import no.entur.abt.bob.mts7.api.UnexpectedCardResponseException;
import no.entur.abt.bob.mts7.simple.api.Mts7ApduExchanges;

/**
 * 
 * Factory which issues commands to an MTS7 card and collects the responses without analyzing anything more than the response codes.
 * 
 */

public class Mts7ApduExchangesFactory {

	public static final byte[] SELECT_BOB_COMMAND = new byte[] { 0x00, (byte) 0xA4, 0x04, 0x00, 0x06, (byte) 0xA0, 0x00, 0x00, 0x07, (byte) 0x81, 0x01 };
	public static final byte[] GET_DATA_COMMAND = new byte[] { 0x00, (byte) 0xCA, 0x7F, 0x21, 0x00, 0x00, 0x00 };
	public static final byte[] GET_NEXT_DATA_COMMAND = new byte[] { 0x00, (byte) 0xCC, 0x7F, 0x21, 0x00, 0x00, 0x00 };
	public static final byte[] GET_RESPONSE_COMMAND = new byte[] { 0x00, (byte) 0xC0, 0x00, 0x00, 0x00, 0x00, 0x00 };
	public static final byte[] INTERNAL_AUTHENTICATE_COMMAND_PREFIX = new byte[] { 0x00, (byte) 0x88, 0x00, 0x00, 0x20 };
	public static final byte[] INTERNAL_AUTHENTICATE_COMMAND_POSTFIX = new byte[] { 0x00 };

	protected final Random random;

	public Mts7ApduExchangesFactory(Random random) {
		this.random = random;
	}

	public Mts7ApduExchangesFactory() {
		this(new SecureRandom());
	}

	public Mts7ApduExchanges createCard(Mts7Exchange mts7Exchange, byte[] selectApplicationResponse) throws IOException, Mts7Exception {
		DefaultMts7Exchange card = new DefaultMts7Exchange(mts7Exchange);

		handleSelectApplication(selectApplicationResponse, card);

		handleGetNextData(card);

		handleInternalAuthenticate(card);

		return card;
	}

	protected void handleInternalAuthenticate(DefaultMts7Exchange card) throws IOException, UnexpectedCardResponseException {
		// 4.1.4. INTERNAL AUTHENTICATE
		// The INTERNAL AUTHENTICATE command is used to authenticate the PICC to the terminal using the
		// cardholder private key.
		// The Authentication Input to INTERNAL AUTHENTICATE is generated by the terminal and SHALL be
		// a SHA-256 hash. Appendix B outlines an example of a JSON object containing appropriate
		// information.
		// • For ECDSA-capable PICCs the hash value is used as Authentication Input,
		// • For PICCs relying on RSA the Travel card application MUST pad the Authentication Input to
		// the length of the modulus in accordance with PKCS#1 version 1.5. The Travel card application
		// MUST also verify the Authentication Input is in compliance with PKCS#1 provisions or
		// otherwise reject the operation.

		byte[] internalAuthenticateCommand = createInternalAuthenticateCommand();
		byte[] internalAuthenticateResponse = card.transceive(internalAuthenticateCommand); // File Control Information (FCI) Template
		if (!isSuccess(internalAuthenticateResponse)) {
			// TODO we might have sent an illegal command - handle encoding for RSA
			throw new UnexpectedCardResponseException(internalAuthenticateCommand, internalAuthenticateResponse);
		}
	}

	protected void handleGetNextData(DefaultMts7Exchange card) throws IOException, UnexpectedCardResponseException {
		byte[] getNextDataResponse = card.transceive(GET_NEXT_DATA_COMMAND); // File Control Information (FCI) Template

		/**
		 * 4.1.3. GET RESPONSE If the status bytes from a GET DATA command is 61xx then there are more bytes to read than what is in the buffer. The remainder
		 * can be retrieved using GET RESPONSE
		 */

		if (isContinue(getNextDataResponse)) {
			do {
				byte[] getResponseResponse = card.transceive(GET_RESPONSE_COMMAND);

				if (isContinue(getResponseResponse)) {
					continue;
				}

				if (!isSuccess(getResponseResponse)) {
					throw new UnexpectedCardResponseException(GET_RESPONSE_COMMAND, getResponseResponse);
				}
				return;
			} while (true);
		}

		if (!isSuccess(getNextDataResponse)) {
			throw new UnexpectedCardResponseException(GET_NEXT_DATA_COMMAND, getNextDataResponse);
		}

	}

	protected void handleSelectApplication(byte[] selectApplicationResponse, DefaultMts7Exchange card) throws IOException, UnableToSelectApplicationException {
		if (selectApplicationResponse == null) {
			selectApplicationResponse = card.transceive(SELECT_BOB_COMMAND); // File Control Information (FCI) Template
		} else {
			card.add(SELECT_BOB_COMMAND, selectApplicationResponse);
		}
		if (!isSuccess(selectApplicationResponse)) {
			throw new UnableToSelectApplicationException(SELECT_BOB_COMMAND, selectApplicationResponse);
		}
	}

	protected byte[] createInternalAuthenticateCommand() {
		ByteArrayOutputStream bout = new ByteArrayOutputStream(128);
		bout.write(INTERNAL_AUTHENTICATE_COMMAND_PREFIX, 0, INTERNAL_AUTHENTICATE_COMMAND_PREFIX.length);

		byte[] payload = new byte[32];
		random.nextBytes(payload);

		bout.write(payload, 0, payload.length);
		bout.write(INTERNAL_AUTHENTICATE_COMMAND_POSTFIX, 0, INTERNAL_AUTHENTICATE_COMMAND_POSTFIX.length);

		return bout.toByteArray();
	}

	protected static boolean isContinue(byte[] response) {
		return response.length > 2 && (response[response.length - 2] & 0xFF) == 0x61;
	}

	protected static boolean isSuccess(byte[] response) {
		return response.length >= 2 && (response[response.length - 2] & 0xFF) == 0x90 && (response[response.length - 1] & 0xFF) == 0x00;
	}
}
